"""Controllo quotidiano della pipeline (#31): apre o aggiorna un'issue quando qualcosa si è fermato, la chiude
quando tutto riparte. Nessun avviso per un import semplicemente indietro: solo se non avanza.

Variabili: DATABASE_URL, GITHUB_TOKEN (issues: write, actions: read), GITHUB_REPOSITORY.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from datetime import UTC, datetime, timedelta

API = "https://api.github.com"
TITOLO = "⚠️ Qualcosa si è fermato"
ETICHETTA = "avviso"
GIORNI_VECCHI = 7  # voti più vecchi di così vanno ancora importati
ORE_FERMO = 24  # e se nessuna votazione nuova arriva da tanto, l'import non avanza


def problemi_import(ultime: dict[str, tuple[datetime, datetime]], adesso: datetime) -> list[str]:
    """ultime: {ramo: (data dell'ultima votazione, quando è stata registrata l'ultima)}."""
    out = []
    for ramo in ("camera", "senato"):
        if ramo not in ultime:
            out.append(f"**{ramo}**: nessuna votazione importata.")
            continue
        data, registrata = ultime[ramo]
        if adesso - data > timedelta(days=GIORNI_VECCHI) and adesso - registrata > timedelta(hours=ORE_FERMO):
            out.append(
                f"**{ramo}**: i voti arrivano solo al {data:%Y-%m-%d} e nessuna votazione nuova è arrivata "
                f"dalle {registrata:%Y-%m-%d %H:%M} UTC. L'import non avanza."
            )
    return out


def problemi_workflow(ultimi: dict[str, dict | None]) -> list[str]:
    """ultimi: {nome workflow: ultimo run concluso (dal JSON dell'API) o None}."""
    out = []
    for nome, run in ultimi.items():
        if run and run.get("conclusion") == "failure":
            out.append(f"**{nome}**: l'ultimo run è fallito ({run['html_url']}).")
    return out


def _gh(metodo: str, url: str, token: str, dati: dict | None = None) -> dict | list:
    req = urllib.request.Request(
        url if url.startswith("http") else API + url,
        method=metodo,
        data=json.dumps(dati).encode() if dati is not None else None,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json", "User-Agent": "op-controllo"},
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        corpo = r.read()
        return json.loads(corpo) if corpo else {}


def main() -> int:
    import psycopg

    token, repo = os.environ["GITHUB_TOKEN"], os.environ["GITHUB_REPOSITORY"]
    adesso = datetime.now(UTC)
    with psycopg.connect(os.environ["DATABASE_URL"]) as c:
        righe = c.execute(
            "select ramo, max(data), max(registrato_il) from core.votazione where legislatura = 19 group by ramo"
        ).fetchall()
    ultime = {r: (datetime.combine(d, datetime.min.time(), UTC), reg) for r, d, reg in righe}

    ultimi = {}
    for wf in ("database.yml", "rilascio.yml", "deploy-web.yml"):
        runs = _gh("GET", f"/repos/{repo}/actions/workflows/{wf}/runs?branch=main&status=completed&per_page=5", token)
        conclusi = [r for r in runs.get("workflow_runs", []) if r["conclusion"] != "cancelled"]  # type: ignore[union-attr]
        ultimi[wf] = conclusi[0] if conclusi else None

    problemi = problemi_import(ultime, adesso) + problemi_workflow(ultimi)
    aperte = _gh("GET", f"/repos/{repo}/issues?labels={ETICHETTA}&state=open", token)
    firma = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    if problemi:
        corpo = (
            f"Controllo automatico del {adesso:%Y-%m-%d %H:%M} UTC.\n\n" + "\n".join(f"- {p}" for p in problemi) + firma
        )
        if aperte:
            _gh("PATCH", f"/repos/{repo}/issues/{aperte[0]['number']}", token, {"body": corpo})  # type: ignore[index]
        else:
            _gh("POST", f"/repos/{repo}/issues", token, {"title": TITOLO, "body": corpo, "labels": [ETICHETTA, "trasversale", "da-fare"]})
        print("\n".join(problemi))
    else:
        for i in aperte:  # type: ignore[union-attr]
            _gh("POST", f"/repos/{repo}/issues/{i['number']}/comments", token, {"body": "Tutto ripartito." + firma})
            _gh("PATCH", f"/repos/{repo}/issues/{i['number']}", token, {"state": "closed", "state_reason": "completed"})
        print("Tutto in ordine.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
